"""fix base for all models

Revision ID: 2deb5e30fc17
Revises: a6b07c74c303
Create Date: 2025-05-31 23:39:30.814975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2deb5e30fc17'
down_revision = 'a6b07c74c303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
