"""initial

Revision ID: a0cb52818fe0
Revises: 
Create Date: 2025-05-31 23:03:39.497301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0cb52818fe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    op.create_table(
        'form_fields',
        sa.Column('name', sa.String(length=50), primary_key=True),
        sa.Column('label', sa.String(length=100), nullable=False),
        sa.Column('is_required', sa.Boolean(), nullable=False, default=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('field_type', sa.String(length=20), nullable=False, default="text"),
    )
    op.execute("""
        INSERT INTO form_fields (name, label, is_required, is_active, field_type) VALUES
        ('username', 'Username', 1, 1, 'text'),
        ('email', 'Email', 1, 1, 'email'),
        ('password', 'Password', 1, 1, 'password'),
        ('consent_lgpd', 'LGPD Consent', 1, 1, 'checkbox')
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_fields')
    # ### end Alembic commands ###
